version: '3.8'
services:
  movies:
    image: rajeshr3f16/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: rajeshr3f16/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: rajeshr3f16/paytmrecharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    image: rajeshr3f16/paytmdth:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
